application: myebirdfeed
version: alpha-1
runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /
  static_files: static/index.html
  upload: static/index\.html

- url: /.*
  script: _go_app
